{
 "title": "Pizza Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{level=\"info\"} |= `` | json"
    }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "requests_total", "legendFormat": "__auto" },
    { "expr": "requests_GET_total", "legendFormat": "__auto" },
    { "expr": "requests_PUT_total", "legendFormat": "__auto" },
    { "expr": "requests_POST_total", "legendFormat": "__auto" },
    { "expr": "requests_DELETE_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    { "expr": "active_users_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    { "expr": "auth_success_total", "legendFormat": "__auto" },
    { "expr": "auth_fail_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "service_latency_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU and memory usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "memory_percent", "legendFormat": "__auto" },
    { "expr": "cpu_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "pizza_latency_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 24 },
   "targets": [
    { "expr": "pizza_success_total", "legendFormat": "__auto" },
    { "expr": "pizza_failure_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Revenue",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 5, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pizza_revenue_total", "legendFormat": "__auto" }
   ]
  }
 ]
}